import os
from datetime import datetime
from urllib.parse import urlparse
from config import OUTPUT_DIR

def generate_html_report(target_url, visited_urls):
    """Generate HTML report from scan results"""
    # Create output directory if not exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = os.path.join(OUTPUT_DIR, f"scan_report_{timestamp}.html")
    
    # Calculate depths and unique paths
    depths = [urlparse(url).path.count('/') for url in visited_urls]
    max_depth = max(depths) if depths else 0
    unique_paths = len(set(urlparse(url).path for url in visited_urls))
    
    # Create HTML content
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Burp Suite Scan Report</title>
        <meta charset="UTF-8">
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
            .container {{ max-width: 1200px; margin: 0 auto; }}
            header {{ background: #2c3e50; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
            h1, h2 {{ color: #2c3e50; }}
            .summary {{ background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px; }}
            .card {{ background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); padding: 20px; margin-bottom: 20px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }}
            th {{ background-color: #3498db; color: white; }}
            tr:hover {{ background-color: #f1f8ff; }}
            .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }}
            .stat-box {{ background: white; border-radius: 8px; padding: 15px; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }}
            .stat-value {{ font-size: 24px; font-weight: bold; color: #3498db; }}
            .stat-label {{ font-size: 14px; color: #7f8c8d; }}
            footer {{ text-align: center; margin-top: 30px; color: #7f8c8d; font-size: 14px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <header>
                <h1>Burp Suite Scan Report</h1>
            </header>
            
            <div class="card">
                <div class="stats">
                    <div class="stat-box">
                        <div class="stat-value">{len(visited_urls)}</div>
                        <div class="stat-label">Pages Scanned</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">{max_depth}</div>
                        <div class="stat-label">Max Depth</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">{unique_paths}</div>
                        <div class="stat-label">Unique Paths</div>
                    </div>
                </div>
            </div>
            
            <div class="card">
                <h2>Scan Summary</h2>
                <p><strong>Target URL:</strong> {target_url}</p>
                <p><strong>Scan Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Scan Duration:</strong> Approximately {len(visited_urls) * 3} seconds</p>
            </div>
            
            <div class="card">
                <h2>Scanned Pages</h2>
                <table>
                    <tr>
                        <th>URL</th>
                        <th>Depth</th>
                    </tr>
                    {"".join(
                        f'<tr><td>{url}</td><td>{urlparse(url).path.count("/")-1}</td></tr>'
                        for url in visited_urls
                    )}
                </table>
            </div>
            
            <div class="card">
                <h2>Next Steps</h2>
                <ol>
                    <li>Review HTTP history in Burp Suite</li>
                    <li>Examine potential vulnerabilities</li>
                    <li>Export findings from Burp Suite</li>
                    <li>Share this report with security team</li>
                </ol>
            </div>
            
            <footer>
                Report generated by Burp Automation Scanner
            </footer>
        </div>
    </body>
    </html>
    """
    
    # Save report
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"📊 Report generated: {report_path}")
    return report_path